### ISSUE TITLE
openLCA 使用官方数据,无法正常搜索中文工序

### ISSUE THREAD

**Issue by jrd77** [linancn/TianGong-LCA-Data#2]
你好
我按照官方教程使用官方数据时,无法复现这一步骤
[教程](https://www.tiangong.earth/zh/post/教程详解-如何在openlca使用天工数据？)
**具体操作: [生产系统->新建->参考的工序->输入'砖']** 
**表现:** 无法查询到对应的[烧结砖工艺],只能输入英文搜索
 如图

![mine](https://github.com/linancn/TianGong-LCA-Data/assets/31362171/328b90a9-47e7-4154-b5b6-3b35309bfaee)
中文无法搜索
![openclamine](https://github.com/linancn/TianGong-LCA-Data/assets/31362171/fbf88300-4239-46f5-a707-924e463717e3)
英文可以

**期望:** 希望可以正常展示搜索中文工序,谢谢

![官方](https://github.com/linancn/TianGong-LCA-Data/assets/31362171/92fe6db4-7d5f-4d14-b8a9-907384d39207)

**Comment by changmillet** [comment]
您好，
感谢您的反馈。我们教程中使用的是openLCA v2.0.4版本，在该版本中，设置中文界面后导入的数据会包含中文信息，从而支持中文检索，如教程所示。
目前openLCA发布的最新版本v2.1.1中（即您截图中使用的版本），中文显示功能仅限于界面显示，尚不支持数据库的双语导入和显示，数据库内容仅能导入和展示英文信息。
目前如有使用需求，您可以通过天工的soda4lca平台用中文检索相关的单元过程，然后用对应的英文名称在openlca中检索建模。

**Comment by jrd77** [comment]
> 您好， 感谢您的反馈。我们教程中使用的是openLCA v2.0.4版本，在该版本中，设置中文界面后导入的数据会包含中文信息，从而支持中文检索，如教程所示。 目前openLCA发布的最新版本v2.1.1中（即您截图中使用的版本），中文显示功能仅限于界面显示，尚不支持数据库的双语导入和显示，数据库内容仅能导入和展示英文信息。 目前如有使用需求，您可以通过天工的soda4lca平台用中文检索相关的单元过程，然后用对应的英文名称在openlca中检索建模。

好的,谢谢

**Comment by yanboy-dev** [comment]
hi！
由于新版本的 openlca 将简体中文 language code 从 `zh` 改为了 `zh_cn`，导致软件在导入数据时无法正确的识别 xml 文件中的 `xml:lang="zh"`.

我将所有数据 xml 中的

```
xml:lang="zh"
```

改为

```
xml:lang="zh_cn"
```
之后，新版的 openlca (v2.3.0) 可以正确的以中文显示并检索数据了.

openlca 的改动可以在这里找到:
- https://github.com/GreenDelta/olca-app/pull/373
- https://github.com/GreenDelta/olca-app/pull/373/commits/da3f60ef557ece641b60cafed360d17aee64fecd

请考虑是否要在今后的数据库版本中进行更改 `xml:lang` 属性 :smile:
